name: Build Dev Container

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/devcontainer/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: "write"
      contents: "read"
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v1

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare DevPod
        run: |
          curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" \
            && sudo install -c -m 0755 devpod /usr/local/bin \
            && rm -f devpod
          devpod provider add docker

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
      - run: |
          devpod build . --devcontainer-path .github/devcontainer/devcontainer.json --repository "devpodhugoboss.azurecr.io/devpod-hugo-boss/devops" --platform linux/amd64
          # Change tag to `latest`
          ID=$(docker images --format "{{.ID}} {{.CreatedAt}} {{.Tag}}" | sort -rk 2 | grep "devpod" | awk 'NR==1{print $1}')
          echo "found image: $ID"
          if [ -z "${ID}" ]; then
            echo "Image ID empty, exiting"
            exit 0 
          fi 
          docker image ls
          docker tag $ID devpodhugoboss.azurecr.io/devpod-hugo-boss/devops:latest
          docker push devpodhugoboss.azurecr.io/devpod-hugo-boss/devops:latest
